### ISSUE TITLE
QuickJS

### ISSUE THREAD

**Issue by zettelmuseum** [SuperIlu/DOjS#11]
Are you familiar with QuickJS? 

https://bellard.org/quickjs/
https://bellard.org/quickjs/bench.html

Looks like is much faster and much more standards compliant than mujs/duktape.
No idea how well it would work in DJGPP, though. Will have a closer look some time..

**Comment by SuperIlu** [comment]
I did a quick test with QuickJS and if I remember right it didn't compile with DJGPP. I'm planing to migrate to Duktape (for now). But before doing this I have some more testing on my list. This still includes QuickJS.

See here for some benchmarks: https://twitter.com/dec_hl/status/1203440011678552067

**Comment by SuperIlu** [comment]
Oh, and when I tried QuickJS (not on DOS though) it was slower than Duktape: https://twitter.com/dec_hl/status/1202292770834137096

**Comment by zettelmuseum** [comment]
Yes, I just tested this - mandel.js from duktape distribution is -slightly- slower.
However, I think this is a special case, maybe because of heavy floating point complex math, or because that benchmark was carefully crafted especially for duktape.
I tried some more scripts, and all were much faster in quickjs.See for example 
https://pastebin.com/xLSr4RUN
It is about 3 times faster.

**Comment by zettelmuseum** [comment]
I tried some more scripts, some were much faster in quickjs, but quite a few were faster in duktape. So I think I was too enthusiastic (maybe because Fabrice Bellard is a legend. I'm using his tiny c compiler in dosbox and it's incredibly fast.)

**Comment by SuperIlu** [comment]
For now Duktape is my favorite because I already ported my other project (jSH) successfully to it.

**Comment by SuperIlu** [comment]
I benchmarked Duktape again (Linux and DOS) and (after some speed improvements over MUjS) I did a full port of DOjS to Duktape.
Sadly this port turned out slower than the current. See my Twitter for a **very** short summary...
https://twitter.com/dec_hl/status/1260943621030887428
