### ISSUE TITLE
Any plans to include TCP/IP capability?

### ISSUE THREAD

**Issue by keenmaster486** [SuperIlu/DOjS#12]
It would be very nice to be able to interface with a packet driver, open websockets to an IP address, send and receive bytes, etc... do you have plans to include this capability? I know things like WattTCP and picoTCP do exist that could be used.

Also something that could be done, though I'm not sure how difficult this is, is to also include the capability to use Windows 9x websockets if the program is running on Windows. I do know that it is possible to do this from a DOS program running on Windows.

**Comment by SuperIlu** [comment]
It is right on the "planed work" list of the readme. For now http://www.watt-32.net/ seems to be a viable option...

**Comment by SuperIlu** [comment]
V1.2.0 with TCP/IP support was just released.
