### ISSUE TITLE
Disabling the cursor

### ISSUE THREAD

**Issue by Regan-Koopmans** [SuperIlu/DOjS#13]
Firstly I would just like to congratulate @SuperIlu on the work that has been done to date. This project is really awesome!

Is there a way to disable the cursor during runtime? I can see how it might be useful in many cases, but I would like to hide it for some situations.

![image](https://user-images.githubusercontent.com/14137201/89096127-689f0180-d3d4-11ea-915b-997879ce4e55.png)

**Comment by SuperIlu** [comment]
The mouse cursor can be disabled by using `MouseShowCursor(false)`. To re-enable it call `MouseShowCursor(true)`.

As you might have noticed from the screenshot there are sometimes issues with displaying the cursor correctly. I haven't figured out what causes this, yet...
