### ISSUE TITLE
nanojpg

### ISSUE THREAD

**Issue by zettelmuseum** [SuperIlu/DOjS#16]
have you been thinking about including jpeg support?
we have png, but those can get rather large..
this looks nice:
http://keyj.emphy.de/nanojpeg/

(by the way, have you tried compiling sqlite3.exe shell using your compiler flags? there's no recent dos compile of that anywhere; 
i tried loading sqlite.dxe with jsh but it didn't work)

**Comment by SuperIlu** [comment]
I ignored JPEG support in the old monolithic DOjS for space reasons. But including it into modular DOjS has no such problems, so I will try that soon. Only problem is I need that feature as a plugin to liballegro...

As for the other Question:
- I can try to create a DOS build of sqlite3.exe and upload that as a separate project, yes
- DOjS and jSH modules are not compatible, sorry. But there is an unreleased version of jSH on my HDD which also includes SQLite. I might release that soon as well...

**Comment by SuperIlu** [comment]
FYI: jSH with SQLite is now available: https://github.com/SuperIlu/jSH/releases/tag/v0.7

**Comment by zettelmuseum** [comment]
maybe this? the readme looks like it could work with dos allegro
https://github.com/dmitrysmagin/allegro/tree/4.4-gcw0/addons/jpgalleg

**Comment by SuperIlu** [comment]
For a DOS/32 build of sqlite3.exe please see this new project: https://github.com/SuperIlu/DOSQLite

**Comment by SuperIlu** [comment]
jpgalleg is sadly not compatible with allegro 4.2.2. I will look into nanojpeg and other possible solutions soon...

**Comment by SuperIlu** [comment]
DXE with nanojpeg loading will be included in the next release...

**Comment by SuperIlu** [comment]
implemented in V1.6.0
