### ISSUE TITLE
OpenGL support

### ISSUE THREAD

**Issue by thp** [SuperIlu/DOjS#19]
Might be fun to have OpenGL available, possibly with WebGL-like bindings.

OSMesa can be built with DJGPP, probably at least the "softpipe" driver should work for DOS (not sure if llvmpipe works): https://docs.mesa3d.org/osmesa.html

There's some example code and a static library available here for faster integration:
https://bisqwit.iki.fi/jutut/kuvat/programming_examples/walk.cc

**Comment by SuperIlu** [comment]
many OpenGL 1.1 functions are included in 1.8.0 release
