### ISSUE TITLE
DOjS Package problem

### ISSUE THREAD

**Issue by shidel** [SuperIlu/DOjS#20]
I was going to update the repository from version 1.6.1 to the latest version 1.7.0. However, there is a problem. It appears you inadvertently included a couple non-redistributable files in the release package. You will want to correct that as soon as possible.

**Comment by SuperIlu** [comment]
Damn, pulled the FDOS package from GitHub, will reupload on the weekend, thanks for noticing...

**Comment by shidel** [comment]
No problem.

In todays super fast internet speeds, it is easy not to notice when uploading/downloading that there is a couple more megabyte than intended. The only reason I noticed was that in preparation to uploading to the package staging repository, it runs a process to preserves file time stamps. I just happen to see those filenames scroll past and though... Wait a second, that can't be right. 

Since you pulled it and will be uploading a fixed version later, you can go ahead and close this issue.

:-)
