### ISSUE TITLE
Compilation Problems take 2

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [SuperIlu/DOjS#3]
its not a matter of using it... its a matter of not spreading garbage in the world... i would not use a project that is as dumb as requiring win10 to compile something for DOS... so without that fixed... i can't promote... to the contrary... all my reviews of the project would be terrible... and so on...

so dont make garbage for DOS... if you are not ready to honor people that code for DOS.... you are just destroying the meaning of all of it... so PLEASE STOP MAKING DOS STUFF if you will act like retarded against DOS

**Comment by SuperIlu** [comment]
Again: watch your language!

Don't use Windows 10 if you don't want to. The instructions work fine with any modern Linux.
