### ISSUE TITLE
Can't use let or const

### ISSUE THREAD

**Issue by seek-Love** [SuperIlu/DOjS#40]
I'm going to guess it's because I'm doing something wrong, but writing something like "const thing = 1;" just gives me an unexpected token error. Is there something I'm missing?

**Comment by SuperIlu** [comment]
Hi, DOjS is based on [MuJS](https://mujs.com/introduction.html) as Javascript runtime.
MuJS only supports [ES5](https://www.w3schools.com/js/js_es5.asp), so no `class`, no `let`, no `const`, etc.
you can replace `let` and `const` by `var` though...
