### ISSUE TITLE
LoadLibrary does not work on 2nd run when using integrated editor

### ISSUE THREAD

**Issue by seek-Love** [SuperIlu/DOjS#41]
Steps to reproduce:

1. dojs newfile.js
2. Add LoadLibrary("curl"); to the top
3. in Setup() declare var https = new Curl();
4. Allow program to run, then exit
5. Run again
6. ReferenceError: 'Curl' is not defined

The issue goes away temporarily if you save the project, close the editor, and reopen, but this becomes understandably tedious

**Comment by SuperIlu** [comment]
Nice catch, I must admit I seldom write code using the editor and I never noticed.
I'll check that and it will hopefully be fixed in the next release (which, sadly, doesn't have a release date yet)...

**Comment by SuperIlu** [comment]
Found and fixed for next release. Give me a nudge if you want an unofficial pre-release...

**Comment by SuperIlu** [comment]
fixed in v1.10.0
