### ISSUE TITLE
/examples/blendfx.js Missing "examples/rose.png"

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [SuperIlu/DOjS#45]
Hi
Just testing out DOjS. This looks great :)

DOjS V1.10.0
Windows 95 OSR2.x, FreeDOS 1.3

The example blendfx.js is missing the rose.png from the examples directory.
Line: 88 rose = new Bitmap("examples/rose.png");

I checked previous versions and has never been included. I tried an arbitrary 400x400px 8-bit 256 color with alpha and receive "Exit code 1" so I haven't gone any further down the rabbit hole :)
I have not tested all examples yet...

I am attempting to work out some other quirks (related) while becoming familiar with DOjS (seperate post).

Kind regards
Axle

**Comment by SuperIlu** [comment]
Thanks for reporting. I tend to fail to include all assets for the example scripts from my private repo
