### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by KormaX-of-DOS** [SuperIlu/DOjS#7]
Thank you for developing for DOS!

Could you please publish the binary as well? I normally work on DOS and don't even have a Windows 10 and especially any Linux PC. I don't have any hope to ever have your program until someone compiles it for me since cross-compiling is not an option and it won't compile on DOS with native DJGPP, at least with these settings and my understanding of C is not deep enough for any trickery.

Thank you :)

**Comment by SuperIlu** [comment]
All the binaries are available on the GitHub release page:
https://github.com/SuperIlu/DOjS/releases
