### ISSUE TITLE
Execute external program

### ISSUE THREAD

**Issue by p-korzeniewski** [SuperIlu/DOjS#8]
Is it possible to execute external program and use the returned value? Something like `var val = exec('time')`.

**Comment by SuperIlu** [comment]
This is not implemented in DOjS right now, but in jSH (the sibling project of DOjS).
I can add a function that calls DJGPPs system(), but maybe you can describe your use-case some more?
system() is not able to return the stdout/stderr of the program run by it and the graphical output of DOjS would freeze while the external program runs...

see http://www.delorie.com/djgpp/doc/libc/libc_802.html for a description of system()

**Comment by p-korzeniewski** [comment]
My use case is a bit crazy :) I have an idea to make a remote browser client for DOS and I'm evaluating possible solutions, the simpler the better. My idea with DOjS is that a) it would call in intervals (in the Loop function) an external program (wget, curl or something similar) that sends a request to remote browser and receives a screenshot to render; b) when input occurs it calls the external program to send a request with mouse position or key pressed to the remote browser. 
The mentioned `system()` unfortunately isn't good enough because it doesn't return the output..

**Comment by SuperIlu** [comment]
Well, you would need to save the data acquired by e.g. wget to a temporary directory and then you can load it from DOjS after the external program returns.
Performance would be, as already mentioned, atrocious :-)

The integrated IPX support is IMHO no help, but integrating something like mTCP into DOjS is on my TODO-List...

**Comment by p-korzeniewski** [comment]
Saving data to a file would work, sluggishly, but still :) sooo will you add the `system()` function in next release?

**Comment by SuperIlu** [comment]
I already did implement it (just copied it from jSH), I have no date set for the next release, though.
If you need that feature fast I can provide you with unreleased binaries if you drop me a note...

I quickly tried the strategy mentioned above by calling `System("dir >tmp.txt")` and then using `Read("tmp.txt")` to get the output off the command and render it in the canvas.
Works as "fine" as you could expect from such a construct :)

**Comment by p-korzeniewski** [comment]
Actually when I think about it the performance of this hack/workaround shouldn't be an issue because I don't want a realtime "preview" of the browser, just a screenshot refreshed when an input (mouse click or key press) from client occurs. Anyway it would be cool if you could somehow share the binaries with this feature, can't wait to try this crazy idea :D

btw DOjS runs amazingly well on a Toshiba Libretto 110CT (subnotebook from 1998 with 233MHz and 32 MB RAM) using FreeDOS :)

**Comment by SuperIlu** [comment]
I was using it on a Libretto 70ct (120MHz) to make a presentation of DOjS using DOjS :)
I'll try to upload a preview release somewhere this week...

**Comment by p-korzeniewski** [comment]
That's cool! Libretto is an amazing little retro machine :) Will wait for the preview release!

**Comment by SuperIlu** [comment]
Please try this (very untested) preview release. 
[dojs.zip](https://github.com/SuperIlu/DOjS/files/4221248/dojs.zip)

**Comment by p-korzeniewski** [comment]
Ok so in general it works, but there is one problem - output of the system call (`wget` in this case) is rendered, even if I try to mute it with `>NUL 2>&1`...

**Comment by SuperIlu** [comment]
Damn, I only tested in DOSBox. I might look into that on the weekend, but I don't have high hopes...

**Comment by p-korzeniewski** [comment]
I have found a solution/workaround - I call `CTTY NUL` before the commands to change the terminal device to nothing and `CTTY CON` after to switch back to console, but now I have another problem :D I call PictView (1.94) to convert jpg image to bmp (`pictview img.jpg -w --o img.bmp`) and once its finished, the mouse stops working, but keyboard works fine (I receive `Input` events)

**Comment by SuperIlu** [comment]
seems like pictview grabs the mouse while running and that breaks mouse support in Allegro. Can't you convert on the computer you download from?

**Comment by p-korzeniewski** [comment]
I could, but the bmp file is quite big and currently I get download speeds of ~40kb/s on Libretto (must investigate why). I tried unloading the CuteMouse driver before running PictView and loading after but without success.. I wonder if it would be possible to add a method to somehow restart the mouse in DOjS? I see that there are `al_install_mouse` & `al_uninstall_mouse` functions in Allegro

**Comment by SuperIlu** [comment]
you are right, I might be able to mitigate that (and other possible problems) by shutting down parts of allegro and restarting them. I'll provide you with an updated preview in the next days...

**Comment by SuperIlu** [comment]
This is the next (completely) untested iteration: 
[dojs.zip](https://github.com/SuperIlu/DOjS/files/4237898/dojs.zip)


You should now be able to do `System("some commando", SYSTEM.MOUSE | SYSTEM.KEYBOARD);` and then the mouse and keyboard handlers are de-registered prior to calling the external program and re-installed after that. Take a look at `jsboot/func.js` for all flags.

**Comment by p-korzeniewski** [comment]
Works like a charm! I wonder if it wouldn't be more useful to make a separate function for installing/deinstalling the mouse and keyboard handlers, I can imagine use cases when someone would want to disable mouse/keyboard for a while.

**Comment by SuperIlu** [comment]
Well, you can hide the mouse pointer and you can just ignore the input events, same effect.
The `System()`-function is a crude hack and I don't want to expose to much low-level Allegro if possible.

But thanks for testing, I'll close this issue with the next release...

**Comment by p-korzeniewski** [comment]
True, exposing low-level stuff isn't the best idea and the solution you mentioned is sufficient.

Thanks for helping me so fast with these edge cases, I can now continue working on my crazy project! :D

**Comment by SuperIlu** [comment]
Included in V1.00 release.

**Comment by SuperIlu** [comment]
V1.2.0 with TCP/IP support was just released.
Maybe this is helpful for your DOS-Browser use-case?
